-- ==========================
-- Ekstenzije
-- ==========================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================
-- Replika
-- ==========================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'replica_user') THEN
    CREATE ROLE replica_user WITH REPLICATION LOGIN PASSWORD 'replica_pass';
  END IF;
END$$;

-- ==========================
-- Karte
-- ==========================
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_uuid UUID DEFAULT gen_random_uuid(),
    entry_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exit_time TIMESTAMP,
    price NUMERIC(10,2),
    paid BOOLEAN DEFAULT FALSE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tickets TO parking_user;
GRANT ALL PRIVILEGES ON SEQUENCE public.tickets_id_seq TO parking_user;

-- ==========================
-- Izvjestaji
-- ==========================
CREATE TABLE IF NOT EXISTS public.reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    type VARCHAR(10) NOT NULL,-- DAILY | MONTHLY
    peak_hour INT,
    occupancy_rate NUMERIC(5,2),
    avg_duration NUMERIC(10,2),
    revenue NUMERIC(12,2)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.reports TO parking_user;
GRANT ALL PRIVILEGES ON SEQUENCE public.reports_report_id_seq TO parking_user;
