-- ==========================
-- Ekstenzije
-- ==========================
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ==========================
-- Replika
-- ==========================
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'replica_user') THEN
    CREATE ROLE replica_user WITH REPLICATION LOGIN PASSWORD 'replica_pass';
  END IF;
END$$;

-- ==========================
-- Parking occupancy log (ML + simulator)
-- ==========================
CREATE TABLE IF NOT EXISTS parking_occupancy_log (
    id             BIGSERIAL    PRIMARY KEY,
    lot_id         VARCHAR(50)  NOT NULL,
    ts             TIMESTAMP    NOT NULL DEFAULT NOW(),
    occupied_count INT          NOT NULL CHECK (occupied_count >= 0),
    capacity       INT          NOT NULL CHECK (capacity > 0),
    is_holiday     SMALLINT     NOT NULL DEFAULT 0 CHECK (is_holiday IN (0, 1))
);

CREATE INDEX IF NOT EXISTS idx_pol_lot_ts
    ON parking_occupancy_log (lot_id, ts DESC);

-- ==========================
-- Karte
-- ==========================
CREATE TABLE IF NOT EXISTS public.tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_uuid UUID DEFAULT gen_random_uuid(),
    entry_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    exit_time TIMESTAMP,
    price NUMERIC(10,2),
    paid BOOLEAN DEFAULT FALSE
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.tickets TO parking_user;
GRANT ALL PRIVILEGES ON SEQUENCE public.tickets_id_seq TO parking_user;

-- ==========================
-- Izvjestaji
-- ==========================
CREATE TABLE IF NOT EXISTS public.reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_date DATE NOT NULL,
    type VARCHAR(10) NOT NULL,
    peak_hour INT,
    occupancy_rate NUMERIC(5,2),
    avg_duration NUMERIC(10,2),
    revenue NUMERIC(12,2)
);

GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE public.reports TO parking_user;
GRANT ALL PRIVILEGES ON SEQUENCE public.reports_report_id_seq TO parking_user;